repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        name: nbstripout - strip notebook outputs
        description: Strip outputs from Jupyter notebooks
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black-jupyter
        name: black (jupyter notebooks)
        language_version: python3
